name: simple project CI

on:
  push: {}

env:
  GOLANG_VERSION: ~1.22


jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache: true
          cache-dependency-path: go.mod

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Linter
        run: make lint

  test:
    name: Run Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache: true
          cache-dependency-path: go.mod

      - name: Run Tests
        run: make test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache: true
          cache-dependency-path: go.mod

      - name: Create binary file
        run: make bin-build